#
#	Makefile for Windows Visual Studio projects
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

PRE_DIRS	= mpr-dynamic

include     .makedep

cleanExtra:
	rm -rf mpr*/Win32
