/*
    bit.h -- Build It Configuration Header for macosx-x64

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BIT_PRODUCT "mpr"
#define BIT_NAME "Multithreaded Portable Runtime"
#define BIT_COMPANY "Embedthis"
#define BIT_MPR_PRODUCT 1
#define BIT_VERSION "4.0.1"
#define BIT_NUMBER "repos"
#define BIT_MAJOR_VERSION 4
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 1
#define BIT_VNUM 400000001
#define BIT_CONFIG_CMD "bit -d -q -platform macosx-x64 -without all -profile xcode -configure . -gen xcode"
#define BIT_PROFILE "xcode"
#define BIT_CFG_PREFIX "/etc/mpr"
#define BIT_BIN_PREFIX "/usr/lib/mpr/4.0.1/bin"
#define BIT_INC_PREFIX "/usr/lib/mpr/4.0.1/inc"
#define BIT_LOG_PREFIX "/var/log/mpr"
#define BIT_PRD_PREFIX "/usr/lib/mpr"
#define BIT_SPL_PREFIX "/var/spool/mpr"
#define BIT_SRC_PREFIX "/usr/src/mpr-4.0.1"
#define BIT_VER_PREFIX "/usr/lib/mpr/4.0.1"
#define BIT_WEB_PREFIX "/var/www/mpr-default"
#define BIT_EXE ""
#define BIT_SHLIB ".dylib"
#define BIT_SHOBJ ".dylib"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"
#define BIT_MANAGER "manager"
#define BIT_CC_DOUBLE_BRACES 1
#define BIT_CC_DYN_LOAD 1
#define BIT_CC_EDITLINE 1
#define BIT_CC_MMU 1
#define BIT_CC_MTUNE 1
#define BIT_CC_PAM 1
#define BIT_CC_STACK_PROTECTOR 1
#define BIT_CC_SYNC 1
#define BIT_CC_SYNC_CAS 1
#define BIT_CC_UNNAMED_UNIONS 1
#define BIT_CC_WARN_64TO32 1
#define BIT_CC_WARN_UNUSED 1
#define BIT_FEATURE_DOXYGEN 0
#define BIT_FEATURE_DSI 0
#define BIT_FEATURE_MAN 0
#define BIT_FEATURE_MAN2HTML 0
#define BIT_FEATURE_PMAKER 0
#define BIT_FEATURE_SSL 0
#define BIT_FEATURE_CC 1
#define BIT_FEATURE_LINK 1
#define BIT_FEATURE_EJS 1
#define BIT_FEATURE_HTTP 1
#define BIT_FEATURE_MD5 1
#define BIT_FEATURE_MATRIXSSL 0
#define BIT_FEATURE_OPENSSL 0
#define BIT_FEATURE_UTEST 1
